---
kind: pipeline
type: exec
name: aports

platform:
  os: linux

steps:
- name: build
  commands:
    - chown -R $USER .
    - chmod -R +rw .
    - ls -lah .
    - ls -lah terra
    - sudo -u $USER /bin/sh -c "make PACKAGE_DIR=$PACKAGE_DIR terra"
  environment:
    PACKAGE_DIR:
      from_secret: package_dir
    USER:
      from_secret: user

node:
  type: alpine-builder
